#!/usr/bin/env pwsh
# Generated by `espalier render-script`; edits are lost on the next render.
$ErrorActionPreference = 'Stop'

if (-not $env:ESPALIER_ELASTICSEARCH_URL) {
    Write-Error 'ESPALIER_ELASTICSEARCH_URL must be set'
    exit 1
}
$ElasticsearchUrl = $env:ESPALIER_ELASTICSEARCH_URL.TrimEnd('/')
$ElasticsearchAuth = $null
if ($env:ESPALIER_ELASTICSEARCH_API_KEY) {
    $ElasticsearchAuth = "ApiKey $env:ESPALIER_ELASTICSEARCH_API_KEY"
}

if (-not $env:ESPALIER_KIBANA_URL) {
    Write-Error 'ESPALIER_KIBANA_URL must be set'
    exit 1
}
$KibanaUrl = $env:ESPALIER_KIBANA_URL.TrimEnd('/')

function Invoke-EsPut {
    param([string]$Path, [string]$Body)
    $headers = @{ 'Content-Type' = 'application/json' }
    if ($ElasticsearchAuth) { $headers['Authorization'] = $ElasticsearchAuth }
    try {
        Invoke-RestMethod -Method Put -Uri "$ElasticsearchUrl$Path" -Headers $headers -Body $Body | Out-Null
    } catch {
        Write-Error "PUT $Path failed: $($_.Exception.Message)"
        exit 1
    }
}

function Test-Healthy {
    try {
        $health = Invoke-RestMethod -Method Get -Uri "$ElasticsearchUrl/_cluster/health"
    } catch {
        return $false
    }
    if ($health.status -ne 'green' -and $health.status -ne 'yellow') {
        return $false
    }
    if ($KibanaUrl) {
        try {
            $status = Invoke-RestMethod -Method Get -Uri "$KibanaUrl/api/status"
        } catch {
            return $false
        }
        if ($status.status.overall.level -ne 'available') {
            return $false
        }
    }
    return $true
}

function Wait-Healthy {
    $deadline = (Get-Date).AddSeconds(30)
    while ($true) {
        if (Test-Healthy) { return }
        if ((Get-Date) -ge $deadline) {
            Write-Error 'target not healthy within 30s'
            exit 1
        }
        Start-Sleep -Milliseconds 250
    }
}

function Invoke-EsPutEmpty {
    param([string]$Path)
    $headers = @{}
    if ($ElasticsearchAuth) { $headers['Authorization'] = $ElasticsearchAuth }
    try {
        Invoke-RestMethod -Method Put -Uri "$ElasticsearchUrl$Path" -Headers $headers | Out-Null
    } catch {
        Write-Error "PUT $Path failed: $($_.Exception.Message)"
        exit 1
    }
}

function Invoke-KibanaPost {
    param([string]$Path, [string]$Body)
    $headers = @{ 'kbn-xsrf' = 'true'; 'Content-Type' = 'application/json' }
    if ($ElasticsearchAuth) { $headers['Authorization'] = $ElasticsearchAuth }
    try {
        Invoke-RestMethod -Method Post -Uri "$KibanaUrl$Path" -Headers $headers -Body $Body | Out-Null
    } catch {
        Write-Error "POST $Path failed: $($_.Exception.Message)"
        exit 1
    }
}

function Invoke-KibanaImport {
    param([string]$Ndjson)
    $headers = @{ 'kbn-xsrf' = 'true' }
    if ($ElasticsearchAuth) { $headers['Authorization'] = $ElasticsearchAuth }
    $tempFile = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName() + '.ndjson')
    Set-Content -Path $tempFile -Value $Ndjson -Encoding utf8 -NoNewline
    try {
        $response = Invoke-RestMethod -Method Post -Uri "$KibanaUrl/api/saved_objects/_import?overwrite=true" -Headers $headers -Form @{ file = Get-Item $tempFile }
    } catch {
        Write-Error "kibana import failed: $($_.Exception.Message)"
        exit 1
    } finally {
        Remove-Item -Path $tempFile -Force -ErrorAction SilentlyContinue
    }
    if ($response.success -eq $false) {
        Write-Error "kibana import reported failures: $($response | ConvertTo-Json -Depth 10 -Compress)"
        exit 1
    }
}

Wait-Healthy

Write-Output '+ ilm:logs-agent_audit.tool_call-policy'
Invoke-EsPut -Path '/_ilm/policy/logs-agent_audit.tool_call-policy' -Body '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"1d","max_primary_shard_size":"50gb"}}},"delete":{"min_age":"3d","actions":{"delete":{"delete_searchable_snapshot":true}}}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}}'

Write-Output '+ component:logs-agent_audit.tool_call@lifecycle'
Invoke-EsPut -Path '/_component_template/logs-agent_audit.tool_call@lifecycle' -Body '{"template":{"settings":{"index.lifecycle.name":"logs-agent_audit.tool_call-policy"}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

Write-Output '+ component:logs-agent_audit.tool_call@mappings'
Invoke-EsPut -Path '/_component_template/logs-agent_audit.tool_call@mappings' -Body '{"template":{"mappings":{"dynamic":"strict","properties":{"@timestamp":{"type":"date"},"event":{"properties":{"action":{"type":"keyword"},"created":{"type":"date"},"dataset":{"type":"keyword"},"kind":{"type":"keyword"}}},"user":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"}}},"host":{"properties":{"name":{"type":"keyword"},"hostname":{"type":"keyword"}}},"agent_audit":{"properties":{"agent":{"properties":{"provider":{"type":"keyword"},"name":{"type":"keyword"},"account":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"},"email":{"type":"keyword"}}},"organization":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"}}}}},"conversation_id":{"type":"keyword"},"turn_id":{"type":"keyword"},"seal":{"properties":{"key_id":{"type":"keyword"}}},"tool_call":{"properties":{"tool":{"properties":{"name":{"type":"keyword"},"call_id":{"type":"keyword"}}},"input":{"properties":{"text":{"type":"wildcard"},"encrypted_text":{"type":"binary"},"length":{"type":"long"}}},"output":{"properties":{"text":{"type":"wildcard"},"encrypted_text":{"type":"binary"},"length":{"type":"long"}}}}}}}}}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

Write-Output '+ ilm:logs-agent_audit.user_prompt-policy'
Invoke-EsPut -Path '/_ilm/policy/logs-agent_audit.user_prompt-policy' -Body '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"1d","max_primary_shard_size":"50gb"}}},"delete":{"min_age":"3d","actions":{"delete":{"delete_searchable_snapshot":true}}}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}}'

Write-Output '+ component:logs-agent_audit.user_prompt@lifecycle'
Invoke-EsPut -Path '/_component_template/logs-agent_audit.user_prompt@lifecycle' -Body '{"template":{"settings":{"index.lifecycle.name":"logs-agent_audit.user_prompt-policy"}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

Write-Output '+ component:logs-agent_audit.user_prompt@mappings'
Invoke-EsPut -Path '/_component_template/logs-agent_audit.user_prompt@mappings' -Body '{"template":{"mappings":{"dynamic":"strict","properties":{"@timestamp":{"type":"date"},"event":{"properties":{"action":{"type":"keyword"},"created":{"type":"date"},"dataset":{"type":"keyword"},"kind":{"type":"keyword"}}},"user":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"}}},"host":{"properties":{"name":{"type":"keyword"},"hostname":{"type":"keyword"}}},"agent_audit":{"properties":{"agent":{"properties":{"provider":{"type":"keyword"},"name":{"type":"keyword"},"account":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"},"email":{"type":"keyword"}}},"organization":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"}}}}},"conversation_id":{"type":"keyword"},"turn_id":{"type":"keyword"},"seal":{"properties":{"key_id":{"type":"keyword"}}},"user_prompt":{"properties":{"text":{"type":"wildcard"},"encrypted_text":{"type":"binary"},"length":{"type":"long"}}}}}}}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

Write-Output '+ index-template:logs-agent_audit.tool_call'
Invoke-EsPut -Path '/_index_template/logs-agent_audit.tool_call' -Body '{"index_patterns":["logs-agent_audit.tool_call-*"],"data_stream":{},"priority":200,"composed_of":["logs-agent_audit.tool_call@mappings","logs-agent_audit.tool_call@lifecycle"],"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

Write-Output '+ data-stream:logs-agent_audit.tool_call-default'
Invoke-EsPutEmpty -Path '/_data_stream/logs-agent_audit.tool_call-default'

Write-Output '+ index-template:logs-agent_audit.user_prompt'
Invoke-EsPut -Path '/_index_template/logs-agent_audit.user_prompt' -Body '{"index_patterns":["logs-agent_audit.user_prompt-*"],"data_stream":{},"priority":200,"composed_of":["logs-agent_audit.user_prompt@mappings","logs-agent_audit.user_prompt@lifecycle"],"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

Write-Output '+ data-stream:logs-agent_audit.user_prompt-default'
Invoke-EsPutEmpty -Path '/_data_stream/logs-agent_audit.user_prompt-default'

Write-Output '+ kibana import (4): data-view:agent-audit-tool-calls, data-view:agent-audit-user-prompts, search:agent-audit-tool-calls-search, search:agent-audit-user-prompts-search'
Invoke-KibanaPost -Path '/api/saved_objects/tag/espalier:agent-observability-lab?overwrite=true' -Body '{"attributes":{"name":"agent-observability-lab","color":"#6E9BF7"}}'
Invoke-KibanaImport -Ndjson @'
{"id":"agent-audit-tool-calls","type":"index-pattern","managed":false,"attributes":{"name":"Agent Audit — Tool Calls","title":"logs-agent_audit.tool_call-*","timeFieldName":"@timestamp"},"references":[{"type":"tag","id":"espalier:agent-observability-lab","name":"tag-ref-espalier:agent-observability-lab"}],"coreMigrationVersion":"9.4.2"}
{"id":"agent-audit-user-prompts","type":"index-pattern","managed":false,"attributes":{"name":"Agent Audit — User Prompts","title":"logs-agent_audit.user_prompt-*","timeFieldName":"@timestamp"},"references":[{"type":"tag","id":"espalier:agent-observability-lab","name":"tag-ref-espalier:agent-observability-lab"}],"coreMigrationVersion":"9.4.2"}
{"id":"agent-audit-tool-calls-search","type":"search","managed":false,"attributes":{"title":"Agent Audit — Tool Calls","description":"Hook-captured tool calls (logs-agent_audit.tool_call-*).","hits":0,"columns":["user.id","host.name","agent_audit.agent.name","agent_audit.agent.account.name","agent_audit.agent.account.email","agent_audit.agent.organization.name","agent_audit.tool_call.tool.name","agent_audit.tool_call.input.text","agent_audit.tool_call.input.length","agent_audit.tool_call.output.text","agent_audit.tool_call.output.length","agent_audit.seal.key_id","agent_audit.conversation_id","agent_audit.turn_id"],"sort":[["@timestamp","desc"]],"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[],\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"}},"references":[{"name":"kibanaSavedObjectMeta.searchSourceJSON.index","type":"index-pattern","id":"agent-audit-tool-calls"},{"type":"tag","id":"espalier:agent-observability-lab","name":"tag-ref-espalier:agent-observability-lab"}],"coreMigrationVersion":"9.4.2"}
{"id":"agent-audit-user-prompts-search","type":"search","managed":false,"attributes":{"title":"Agent Audit — User Prompts","description":"Hook-captured user prompts (logs-agent_audit.user_prompt-*).","hits":0,"columns":["user.id","host.name","agent_audit.agent.name","agent_audit.agent.account.name","agent_audit.agent.account.email","agent_audit.agent.organization.name","agent_audit.user_prompt.text","agent_audit.user_prompt.length","agent_audit.seal.key_id","agent_audit.conversation_id","agent_audit.turn_id"],"sort":[["@timestamp","desc"]],"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[],\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"}},"references":[{"name":"kibanaSavedObjectMeta.searchSourceJSON.index","type":"index-pattern","id":"agent-audit-user-prompts"},{"type":"tag","id":"espalier:agent-observability-lab","name":"tag-ref-espalier:agent-observability-lab"}],"coreMigrationVersion":"9.4.2"}
'@
