#!/usr/bin/env bash
# Generated by `espalier render-script`; edits are lost on the next render.
set -euo pipefail

: "${ESPALIER_ELASTICSEARCH_URL:?ESPALIER_ELASTICSEARCH_URL must be set}"
ELASTICSEARCH_URL="${ESPALIER_ELASTICSEARCH_URL%/}"
ELASTICSEARCH_AUTH=""
if [ -n "${ESPALIER_ELASTICSEARCH_API_KEY:-}" ]; then
  ELASTICSEARCH_AUTH="ApiKey ${ESPALIER_ELASTICSEARCH_API_KEY}"
fi

: "${ESPALIER_KIBANA_URL:?ESPALIER_KIBANA_URL must be set}"
KIBANA_URL="${ESPALIER_KIBANA_URL%/}"

put_es() {
  local path="$1" body="$2"
  local args=(-sS -w '\n%{http_code}' -X PUT "${ELASTICSEARCH_URL}${path}" -H 'Content-Type: application/json' --data-binary "$body")
  if [ -n "$ELASTICSEARCH_AUTH" ]; then
    args+=(-H "Authorization: ${ELASTICSEARCH_AUTH}")
  fi
  local response status
  response="$(curl "${args[@]}")"
  status="${response##*$'\n'}"
  if [ "$status" -lt 200 ] || [ "$status" -ge 300 ]; then
    echo "error: PUT ${path} failed with HTTP ${status}" >&2
    exit 1
  fi
}

health_check() {
  local body
  body="$(curl -sS "${ELASTICSEARCH_URL}/_cluster/health" 2>/dev/null)" || return 1
  case "$body" in
    *'"status":"green"'*|*'"status":"yellow"'*) ;;
    *) return 1 ;;
  esac
  if [ -n "${KIBANA_URL:-}" ]; then
    body="$(curl -sS "${KIBANA_URL}/api/status" 2>/dev/null)" || return 1
    case "$body" in
      *'"overall":{"level":"available"'*) ;;
      *) return 1 ;;
    esac
  fi
  return 0
}

wait_healthy() {
  local deadline=$(( $(date +%s) + 30 ))
  while :; do
    if health_check; then
      return 0
    fi
    if [ "$(date +%s)" -ge "$deadline" ]; then
      echo "error: target not healthy within 30s" >&2
      exit 1
    fi
    sleep 0.25
  done
}

put_es_empty() {
  local path="$1"
  local args=(-sS -w '\n%{http_code}' -X PUT "${ELASTICSEARCH_URL}${path}")
  if [ -n "$ELASTICSEARCH_AUTH" ]; then
    args+=(-H "Authorization: ${ELASTICSEARCH_AUTH}")
  fi
  local response status
  response="$(curl "${args[@]}")"
  status="${response##*$'\n'}"
  if [ "$status" -lt 200 ] || [ "$status" -ge 300 ]; then
    echo "error: PUT ${path} failed with HTTP ${status}" >&2
    exit 1
  fi
}

post_kibana() {
  local path="$1" body="$2"
  local args=(-sS -w '\n%{http_code}' -X POST "${KIBANA_URL}${path}" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' --data-binary "$body")
  if [ -n "$ELASTICSEARCH_AUTH" ]; then
    args+=(-H "Authorization: ${ELASTICSEARCH_AUTH}")
  fi
  local response status
  response="$(curl "${args[@]}")"
  status="${response##*$'\n'}"
  if [ "$status" -lt 200 ] || [ "$status" -ge 300 ]; then
    echo "error: POST ${path} failed with HTTP ${status}" >&2
    exit 1
  fi
}

import_kibana() {
  local ndjson="$1"
  local args=(-sS -w '\n%{http_code}' -X POST "${KIBANA_URL}/api/saved_objects/_import?overwrite=true" -H 'kbn-xsrf: true' --form 'file=@-;filename=import.ndjson;type=application/ndjson')
  if [ -n "$ELASTICSEARCH_AUTH" ]; then
    args+=(-H "Authorization: ${ELASTICSEARCH_AUTH}")
  fi
  local response status body
  response="$(printf '%s' "$ndjson" | curl "${args[@]}")"
  status="${response##*$'\n'}"
  body="${response%$'\n'*}"
  if [ "$status" -lt 200 ] || [ "$status" -ge 300 ]; then
    echo "error: kibana import failed with HTTP ${status}: ${body}" >&2
    exit 1
  fi
  case "$body" in
    *'"success":false'*)
      echo "error: kibana import reported failures: ${body}" >&2
      exit 1
      ;;
  esac
}

wait_healthy

echo '+ ilm:logs-agent_audit.tool_call-policy'
put_es '/_ilm/policy/logs-agent_audit.tool_call-policy' '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"1d","max_primary_shard_size":"50gb"}}},"delete":{"min_age":"3d","actions":{"delete":{"delete_searchable_snapshot":true}}}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}}'

echo '+ component:logs-agent_audit.tool_call@lifecycle'
put_es '/_component_template/logs-agent_audit.tool_call@lifecycle' '{"template":{"settings":{"index.lifecycle.name":"logs-agent_audit.tool_call-policy"}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

echo '+ component:logs-agent_audit.tool_call@mappings'
put_es '/_component_template/logs-agent_audit.tool_call@mappings' '{"template":{"mappings":{"dynamic":"strict","properties":{"@timestamp":{"type":"date"},"event":{"properties":{"action":{"type":"keyword"},"created":{"type":"date"},"dataset":{"type":"keyword"},"kind":{"type":"keyword"}}},"user":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"}}},"host":{"properties":{"name":{"type":"keyword"},"hostname":{"type":"keyword"}}},"agent_audit":{"properties":{"agent":{"properties":{"provider":{"type":"keyword"},"name":{"type":"keyword"},"account":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"},"email":{"type":"keyword"}}},"organization":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"}}}}},"conversation_id":{"type":"keyword"},"turn_id":{"type":"keyword"},"seal":{"properties":{"key_id":{"type":"keyword"}}},"tool_call":{"properties":{"tool":{"properties":{"name":{"type":"keyword"},"call_id":{"type":"keyword"}}},"input":{"properties":{"text":{"type":"wildcard"},"encrypted_text":{"type":"binary"},"length":{"type":"long"}}},"output":{"properties":{"text":{"type":"wildcard"},"encrypted_text":{"type":"binary"},"length":{"type":"long"}}}}}}}}}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

echo '+ ilm:logs-agent_audit.user_prompt-policy'
put_es '/_ilm/policy/logs-agent_audit.user_prompt-policy' '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"1d","max_primary_shard_size":"50gb"}}},"delete":{"min_age":"3d","actions":{"delete":{"delete_searchable_snapshot":true}}}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}}'

echo '+ component:logs-agent_audit.user_prompt@lifecycle'
put_es '/_component_template/logs-agent_audit.user_prompt@lifecycle' '{"template":{"settings":{"index.lifecycle.name":"logs-agent_audit.user_prompt-policy"}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

echo '+ component:logs-agent_audit.user_prompt@mappings'
put_es '/_component_template/logs-agent_audit.user_prompt@mappings' '{"template":{"mappings":{"dynamic":"strict","properties":{"@timestamp":{"type":"date"},"event":{"properties":{"action":{"type":"keyword"},"created":{"type":"date"},"dataset":{"type":"keyword"},"kind":{"type":"keyword"}}},"user":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"}}},"host":{"properties":{"name":{"type":"keyword"},"hostname":{"type":"keyword"}}},"agent_audit":{"properties":{"agent":{"properties":{"provider":{"type":"keyword"},"name":{"type":"keyword"},"account":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"},"email":{"type":"keyword"}}},"organization":{"properties":{"id":{"type":"keyword"},"name":{"type":"keyword"}}}}},"conversation_id":{"type":"keyword"},"turn_id":{"type":"keyword"},"seal":{"properties":{"key_id":{"type":"keyword"}}},"user_prompt":{"properties":{"text":{"type":"wildcard"},"encrypted_text":{"type":"binary"},"length":{"type":"long"}}}}}}}},"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

echo '+ index-template:logs-agent_audit.tool_call'
put_es '/_index_template/logs-agent_audit.tool_call' '{"index_patterns":["logs-agent_audit.tool_call-*"],"data_stream":{},"priority":200,"composed_of":["logs-agent_audit.tool_call@mappings","logs-agent_audit.tool_call@lifecycle"],"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

echo '+ data-stream:logs-agent_audit.tool_call-default'
put_es_empty '/_data_stream/logs-agent_audit.tool_call-default'

echo '+ index-template:logs-agent_audit.user_prompt'
put_es '/_index_template/logs-agent_audit.user_prompt' '{"index_patterns":["logs-agent_audit.user_prompt-*"],"data_stream":{},"priority":200,"composed_of":["logs-agent_audit.user_prompt@mappings","logs-agent_audit.user_prompt@lifecycle"],"_meta":{"espalier":{"project":"agent-observability-lab"}}}'

echo '+ data-stream:logs-agent_audit.user_prompt-default'
put_es_empty '/_data_stream/logs-agent_audit.user_prompt-default'

echo '+ kibana import (4): data-view:agent-audit-tool-calls, data-view:agent-audit-user-prompts, search:agent-audit-tool-calls-search, search:agent-audit-user-prompts-search'
post_kibana '/api/saved_objects/tag/espalier:agent-observability-lab?overwrite=true' '{"attributes":{"name":"agent-observability-lab","color":"#6E9BF7"}}'
import_kibana '{"id":"agent-audit-tool-calls","type":"index-pattern","managed":false,"attributes":{"name":"Agent Audit — Tool Calls","title":"logs-agent_audit.tool_call-*","timeFieldName":"@timestamp"},"references":[{"type":"tag","id":"espalier:agent-observability-lab","name":"tag-ref-espalier:agent-observability-lab"}],"coreMigrationVersion":"9.4.2"}
{"id":"agent-audit-user-prompts","type":"index-pattern","managed":false,"attributes":{"name":"Agent Audit — User Prompts","title":"logs-agent_audit.user_prompt-*","timeFieldName":"@timestamp"},"references":[{"type":"tag","id":"espalier:agent-observability-lab","name":"tag-ref-espalier:agent-observability-lab"}],"coreMigrationVersion":"9.4.2"}
{"id":"agent-audit-tool-calls-search","type":"search","managed":false,"attributes":{"title":"Agent Audit — Tool Calls","description":"Hook-captured tool calls (logs-agent_audit.tool_call-*).","hits":0,"columns":["user.id","host.name","agent_audit.agent.name","agent_audit.agent.account.name","agent_audit.agent.account.email","agent_audit.agent.organization.name","agent_audit.tool_call.tool.name","agent_audit.tool_call.input.text","agent_audit.tool_call.input.length","agent_audit.tool_call.output.text","agent_audit.tool_call.output.length","agent_audit.seal.key_id","agent_audit.conversation_id","agent_audit.turn_id"],"sort":[["@timestamp","desc"]],"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[],\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"}},"references":[{"name":"kibanaSavedObjectMeta.searchSourceJSON.index","type":"index-pattern","id":"agent-audit-tool-calls"},{"type":"tag","id":"espalier:agent-observability-lab","name":"tag-ref-espalier:agent-observability-lab"}],"coreMigrationVersion":"9.4.2"}
{"id":"agent-audit-user-prompts-search","type":"search","managed":false,"attributes":{"title":"Agent Audit — User Prompts","description":"Hook-captured user prompts (logs-agent_audit.user_prompt-*).","hits":0,"columns":["user.id","host.name","agent_audit.agent.name","agent_audit.agent.account.name","agent_audit.agent.account.email","agent_audit.agent.organization.name","agent_audit.user_prompt.text","agent_audit.user_prompt.length","agent_audit.seal.key_id","agent_audit.conversation_id","agent_audit.turn_id"],"sort":[["@timestamp","desc"]],"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[],\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"}},"references":[{"name":"kibanaSavedObjectMeta.searchSourceJSON.index","type":"index-pattern","id":"agent-audit-user-prompts"},{"type":"tag","id":"espalier:agent-observability-lab","name":"tag-ref-espalier:agent-observability-lab"}],"coreMigrationVersion":"9.4.2"}'
